### ISSUE TITLE
Search text box without border in white color background is very difficult to find (mobile)

### ISSUE THREAD

**Issue by jaykishanparikh** [covid19india/covid19india.github.io#1558]
**Describe the bug**
Home Page search text field is the most important input parameter. Without border this text box is very difficult to find. Especially on iPhone safari

**To Reproduce**
Adding a border will help to identify this field.

**Expected behavior**
Should have border to easy identification

**Screenshots**
![IMG_3355](https://user-images.githubusercontent.com/17736902/80297644-50fa2080-87c8-11ea-9be4-20f91ae79d6b.PNG)

Screenshot attached is from iphone safari.

**How to fix**
1. Add border:1 for the text css.

**Comment by jaykishanparikh** [comment]
Kindly assign this issue to me. Easy and quick fix.

**Comment by jaykishanparikh** [comment]
**Fix**
Filename - App.scss
Line number : 948
border :1;

```css
input {
    -webkit-box-shadow: 0 10px 35px rgba(0, 0, 0, 0.1);
    background: #fff;
    **border: 1;**
    border-radius: 5px;
    box-shadow: 0 10px 35px rgba(0, 0, 0, 0.1);
    color: $gray;
    font-family: 'archia';
    font-size: 1rem;
    height: 2rem;
    outline: none;
    padding: 1rem;
    padding-left: 3rem;
    transition: all 0.2s ease-in-out;
    width: calc(100% - 4rem);
  }
```
**After Fix on my local**
<img src="https://user-images.githubusercontent.com/17736902/80297823-2c06ad00-87ca-11ea-8487-b72bf028c52f.png">
